### ISSUE TITLE
Pages show HTML comments from `config.action_view.annotate_rendered_view_with_filenames`

### ISSUE THREAD

**Issue by thutterer** [allmarkedup/lookbook#112]
Hi there! 👋🏼 I've recently enabled `config.action_view.annotate_rendered_view_with_filenames` in a project that uses Lookbook and noticed that now all markdown pages render the HTML comments from the annotatation in the page as text.

**Example:**

A file `test.md.erb` renders like the image below.

```markdown
# Hello there!

Testing 123.
```

![image](https://user-images.githubusercontent.com/5372947/177770496-88ccf3cb-dbcd-4f02-a9a6-fdbdf244c2e8.png)

This does not happen with `html.erb` files, so it might be an issue in RedCarpet. I found https://github.com/vmg/redcarpet/issues/268 but haven't done any further digging.

Let me know if I can help! Also, thank you for this great project! 🤗

**Comment by allmarkedup** [comment]
Hey @thutterer thanks for this report - this is not something I'd considered so good to have flagged! I think it's because the way Lookbook is treating the markdown as a template (and rendering inline with ERB) before passing it to the markdown renderer, so it must be getting tagged with comments before rendering as markdown.

Pretty sure I can find a fix for this so will get it sorted as soon as I get a chance. Thanks again for bringing it to my attention!

**Comment by allmarkedup** [comment]
@thutterer sorry for taking so long but this should now be fixed in version 0.9.2 - if you are still having any problems after updating please let me know!

**Comment by thutterer** [comment]
@allmarkedup Awesome! Thank you 💯
