### ISSUE TITLE
Template Error within preview window

### ISSUE THREAD

**Issue by magico** [allmarkedup/lookbook#117]
My components get recognized by lookbook but the preview window throws an `ActionView::Template::Error`. This is happening with all my components.

```
No route matches {:action=>"preview", :controller=>"lookbook/previews", :page=>nil, :path=>"button/sizes"}
```  

![2022-08-02 at 11 20 53@2x](https://user-images.githubusercontent.com/944051/182446052-bbb826ce-3ebc-40b8-8fa3-c36643837eca.png)
 
Worth noting that I can see the previews through http://localhost:3000/rails/view_components/ without any issues.

I am currently using lookbook (0.9.3), and just to confirm, my routes are configured as per the documentation:
```
mount Lookbook::Engine, at: "/lookbook"
```

**Comment by allmarkedup** [comment]
Hey @magico - I'm so sorry it has taken so long to get back to you! I have been away on holiday and not had much access to WIFI.

Are you still running into this issue or has it resolved itself now?

**Comment by magico** [comment]
No worries. Everyone deserves some good time off 🙂

Yes, the issue is still happening. For reference, I'm using Rails 7.0.3.1 with ruby 3.1.0 .

**Comment by allmarkedup** [comment]
@magico Hmm I'm afraid to say I'm a little bit stumped by this one, it is not one I've come across before and so far I haven't been able to replicate it. I'm not even really sure how to investigate it without being able to dig in a bit more.

I'll try a fresh Rails 7 / Ruby 3.1.0 install when I have a chance (hopefully later today) and try to replicate it again.

If you have time you could also try the latest [v1.0 beta version](https://github.com/allmarkedup/lookbook/tree/v1.0-beta) to see if you have the same problem. I suspect you might... but you never know :-)

Sorry I can't help more just yet - but I'll let you know as soon as I can if I manage to figure anything out.

**Comment by allmarkedup** [comment]
Hey @magico I just wanted to let you know that I've just released Lookbook v1.0. If you have a chance could you test again using this version and confirm if you are still seeing the same issue or not?

```ruby
gem "lookbook", ">= 1.0.0"
```

Thanks :-)

**Comment by magico** [comment]
Congrats on the v1 launch! 🎉

I did update to 1.0.4 and still have the same issue. What info can I provide to help debug? The request seems to be failing when processing `ViewComponentsController#render_in_layout_to_string`:
```
22:30:01 web.1    | Processing by ViewComponentsController#render_in_layout_to_string as HTML
22:30:01 web.1    |   Parameters: {"lookbook_timestamp"=>"2022-09-08 22:30:00 +0200", "path"=>"button/primary"}
22:30:01 web.1    |   Rendering layout layouts/application.html.erb
22:30:01 web.1    |   Rendering /Users/magico/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/lookbook-1.0.4/app/views/lookbook/preview.html.erb within layouts/application
22:30:01 web.1    |   Rendered /Users/magico/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/lookbook-1.0.4/app/views/lookbook/preview.html.erb within layouts/application (Duration: 0.5ms | Allocations: 322)
22:30:01 web.1    |   Rendered layout layouts/application.html.erb (Duration: 2.0ms | Allocations: 4321)
22:30:01 web.1    | Completed 500 Internal Server Error in 3ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 4900)
```

**Comment by allmarkedup** [comment]
Hey @magico - sorry this is still a problem for you!

Just thinking out loud here but do you have any Rails config in your application that might impact 'standard' routing behaviour and/or helpers?

I know it's a big ask, but is there anyway you could put together a repo with a new Rails app that demonstrates the issue? I just can't seem to recreate it locally but if I had something to dig into I would stand a better chance of being able to debug it.

**Comment by imfishhead** [comment]
Hi @allmarkedup @magico - Good day to both of you!

I've recently encountered this issue too, after tracing I found out that it's caused by exisiting `link_to` inside `application.html.erb` of my existing project, lookbook will be working fine if I use a clean layout:

```
    config.view_component.default_preview_layout = "preview"
```

I'm able to replicate the bug using `lookbook-demo` repo and I've forked to add a `link_to` to replicate this bug
https://github.com/imfishhead/lookbook-demo/commit/0eafa37e6850c1ff0c9f34a46dc76b614e6a4344

This will cause:

![image](https://user-images.githubusercontent.com/7972863/191901220-a39def86-3e70-49ae-ba80-fd9810693069.png)

Hope this helps!

**Comment by allmarkedup** [comment]
@imfishhead thank you so much! That is really a huge help. I'll try to dig into that as soon as I have time and hopefully get a fix or workaround together.

Really appreciate you taking the time to figure it out and get the error demo together. I'll let you know as soon as I've made progress on the issue.

**Comment by magico** [comment]
Ah! Thanks for helping out @imfishhead. I meant to dig into this but had no time recently 😞
I do have a few `link_to` inside `application.html.erb`, so that probably is the same issue.

**Comment by allmarkedup** [comment]
I've added a note to the docs here: https://lookbook.build/guide/troubleshooting/#template-error-in-preview-window which will hopefully help prevent other people from running into the same issue as you both.

Thanks again for all the help in figuring out what the issue was! Really much appreciated 👍

**Comment by imfishhead** [comment]
@allmarkedup Thanks for the effort!

**Comment by cristianbica** [comment]
What's happening here is that if you pass some `Hash` to a `link_to` it will call `url_for` with those params to build the url. Rails will merge the current request params with the params given to `link_to` and try to find a route matching those params. Because we're in the `Lookbook::PreviewController` the params will look like this `{:action=>"preview", :controller=>"lookbook/previews", :page=>nil, :path=>"button/sizes"}`. While these params do match a valid route that route is in the `Lookbook::Engine` not in the main application routes. Therefor rails will not be able to find valid routes (read more [here](https://api.rubyonrails.org/classes/Rails/Engine.html#method-i-routes)).

```ruby
> Rails.application.routes.url_helpers.url_for controller: "lookbook/previews", action: :show, path: "a/b/c", only_path: true
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"lookbook/previews", :path=>"a/b/c"}

> Lookbook::Engine.routes.url_helpers.url_for controller: "lookbook/previews", action: :show, path: "a/b/c", only_path: true
=> "/admin/lookbook/preview/a/b/c"
```

If you really need to workaround this (e.g. you have some `link_to` / `url_for` in a gem) you can define some dummy routes in your rails app:

```ruby
# add this to routes.rb
if Rails.env.development? || Rails.env.test?
  get "/something-very-random/preview/*path", to: "lookbook/previews#show"
  get "/something-very-random/inspector/*path", to: "lookbook/inspector#show"
end
```

**Comment by allmarkedup** [comment]
@cristianbica I appreciate you taking the time to explain that - makes sense. It sounds like there is nothing much I can do from the Lookbook side of things but I'll add your workaround to the troubleshooting page in the docs so that others in the same boat can benefit from it. Many thanks 🙏
