### ISSUE TITLE
Javascript Issue blocking Preview updates

### ISSUE THREAD

**Issue by jonsgreen** [allmarkedup/lookbook#127]
Hey there, I am really excited about this project and looking forward to using it instead of Storybook!

I am running into an issue trying out the latest beta release. If I try to change the text in a params when running locally it is not submitting like it does in the demo app. I am seeing a bunch of javascript errors in the console and I am guessing that could be the problem. Here is what it looks like: 
<img width="1507" alt="Screen Shot 2022-09-02 at 3 32 53 PM" src="https://user-images.githubusercontent.com/3073/188224474-4f408f35-fd39-4dfd-ac97-c625f363368f.png">

Please let me know if you need more information or if there is anyway that I can help!

**Comment by allmarkedup** [comment]
Hey @jonsgreen - thanks for the heads up and sorry your first experience of Lookbook has not been a good one. I'm going to dig into this now, see if I can replicate it locally and then get it fixed.

I'll let you know as soon as I've figured out what is going on. Thanks again :-)

**Comment by allmarkedup** [comment]
@jonsgreen a bit of a tricky one this as I can't seem to replicate your errors locally! Out of interest, have you got any Rails config settings to do with json unescaping set in your app?

However I've spotted a few places where some encoding/escaping issues could creep in and I've (hopefully) fixed those in commit 7672518678c549903c5e099addff8d057982b76c on the `v1.0-beta` branch.

Could you try pulling the gem from that branch and see if it fixes the issue for you?

```
gem "lookbook", git: "git://github.com/allmarkedup/lookbook.git", branch: "v1.0-beta"
```

Thanks for your help with this!

**Comment by allmarkedup** [comment]
@jonsgreen sorry, another update :-) My plan was to release v1.0 this weekend and after improving the params encoding and testing at my end I decided go ahead with the release. So you can now install v1.0.0 directly and (I hope!) the issue should be fixed for you.

```
gem "lookbook", ">= 1.0.0"
```

Let me know how you get on - if you are still running into issues I'll need to take another look at how to replicate locally somehow. Cheers 👍

**Comment by allmarkedup** [comment]
@jonsgreen ok great, thanks for trying that out and for digging about a bit too. It's a bit of a mystery to me why it is affecting you but I can't replicate it here. But would be good to get it fixed regardless as I'm sure you will not be the only one!

There may well have been a reason I used `safe_join` there... but to be honest I really can't remember :-) I'll give your suggestion a try and make sure it hasn't got any unintended side effects, and if it's all good I'll try to get a patch release out as soon as I can.

Appreciate your kind words - it is just a side project for me, no funding sadly! Or perhaps thankfully ;-) The first version was built to scratch my own itch at my job (where we use ViewComponent) and since then it's just been something I've been using to help me learn Ruby. People seem to appreciate it though which is always great for motivation to keep the ball rolling.

I'll update you as soon as I've tested your suggestion, thanks again 👍

**Comment by jonsgreen** [comment]
Thanks for your help @allmarkedup. Just to be clear, I was not really suggesting that you switch to using `args.join` since I am assuming there was some reason for the safe_join. I mostly was offering the information to show that in my case it was the presence of possible `&` from the escaped args that seems to cause the problems.

I was wondering if perhaps my problem could have been just a local issue so I went ahead and deployed the code to our staging environment but got the same issue there. In case it helps you with debugging you can check it out [here](https://grouptourops-staging.herokuapp.com/lookbook) though we may end up removing the code from that environment at some point soon.

**Comment by allmarkedup** [comment]
Thanks @jonsgreen - I've taken a look at your staging environment and done some tests and although I have no idea why it is affecting you and not others, I can't see any reason why using join instead of safe join here would be a problem. I'll get a fix released shortly and let you know when it is done 👍

**Comment by allmarkedup** [comment]
That's great to hear! Glad we managed to get it sorted. Anything else just give me a shout 👍
