### ISSUE TITLE
v0.9.6 - stopped reloading code

### ISSUE THREAD

**Issue by drnic** [allmarkedup/lookbook#131]
A regression appeared recently and I can reproduce it on v0.9.6 but it does not appear in v0.9.5.

Lookbook stopped reloading my source code. If I go to the browser and refresh lookbook, it has the old code. This also affects the autorefresh of lookbook from local changes.

I have a rails 7, view_component 2.71, etc.

https://github.com/allmarkedup/lookbook/compare/v0.9.5...v0.9.6 -- whilst the v0.9.6 code does look to change something in its `engine.rb` relating to listeners, at a glance I cannot see how this code negatively affects me:

```ruby
3.1.2 :001 > Gem::Version.new(Rails.version)
 => Gem::Version.new("7.0.3.1")
3.1.2 :002 > Gem::Version.new("6.1.3.1")
 => Gem::Version.new("6.1.3.1")
3.1.2 :003 > Gem::Version.new(Rails.version) > Gem::Version.new("6.1.3.1")
 => true
```

It looks to invoke `init_listeners` just like it did in v0.9.5.

Anyone else seeing this? Or better, knows what caused it and what's the fix? :)

**Comment by allmarkedup** [comment]
Hey @drnic - sorry you are having problems!

There were some changes in `0.9.6` to do with initialising listeners to fix a bug where they were starting in tests, scripts etc rather than only when running in a server context.

Can you just check one thing for me before I try to debug any further? Your `config.ru` file should have the line `Rails.application.load_server` at the bottom of it. Can you confirm it's in there? The file should look something like

```rb
# This file is used by Rack-based servers to start the application.

require_relative "config/environment"

run Rails.application
Rails.application.load_server
```

Rails apps that have been upgraded from a version earlier than `6.1.3.1` often don't have it in there but it is in all newer `config.ru` file and Lookbook relies on it to run 'server-only' code (as might other gems so it is good to have it in there!).

If that is not the issue then let me know and I'll have a think what else could be going on.

**Comment by drnic** [comment]
Hurray! My app did not have this. I added it, upgraded to 1.0.1, and code reloading is back in action.

My app came from https://jumpstartrails.com/ which I can confirm also doesn't have this extra line. I'll get that fixed upstream for them + other JSP users.

**Comment by allmarkedup** [comment]
@drnic awesome! Really glad that sorted it for you. And I'd really appreciate it if you could get that fixed in the Jumpstart Rails project - I've not see that before but it looks great.

Any other issues or questions just give me a shout :-)

**Comment by drnic** [comment]
Congrats on lookbook + v1.0 release. Great project.

**Comment by allmarkedup** [comment]
Thanks @drnic! Really appreciate it :-)

**Comment by christopherstyles** [comment]
Went ahead and added a PR ([#443](https://github.com/jumpstart-pro/jumpstart-pro-rails/pull/443)) to jumpstart-pro, hope you don’t mind @drnic! I was on a fresh jumpstart install and noticed the issue, so was _in it_ and had the time 😄 

Thanks for an awesome project here @allmarkedup, loving it!!

**Comment by allmarkedup** [comment]
My pleasure @christopherstyles, glad you are enjoy using it :-)
