### ISSUE TITLE
Dynamic previews with metaprogramming / define_method

### ISSUE THREAD

**Issue by Timmitry** [allmarkedup/lookbook#154]
I'm trying to dynamically generate previews with some metaprogramming 😬 Given the following code:

```ruby
class Generic::Icon::ComponentPreview < ViewComponent::Preview
  Generic::Icon::Component::ICONS.each do |icon|
    define_method icon do
      render(Generic::Icon::Component.new(icon:))
    end
  end

  def static
    render(Generic::Icon::Component.new(icon: :gear))
  end
end
```

where

```ruby
ICONS = %i[gear tablet exchange triangle-exclamation].freeze
```

This successfully adds instance methods to the preview, as can be checked with

```ruby
Generic::Icon::ComponentPreview.instance_methods(false)
#=> [:"triangle-exclamation", :gear, :static, :exchange, :tablet]
```

However, lookbook does not pick up those methods, only the `static` one. I would suspect that lookbook does not actually load the ruby file (and therefore does not run the each loop), but only does a static parsing of the file contents? I was just wondering if this might be possible...

An alternativ would be to somehow render multiple components in one preview, but I'm also not sure if this is possible. Something like

```ruby
  def static
    render([
      Generic::Icon::Component.new(icon: :gear),
      Generic::Icon::Component.new(icon: :tablet),
    ])
  end
```

or something similar?

Otherwise this is a really cool gem and works like a charm 🎉

**Comment by allmarkedup** [comment]
Hey @Timmitry - unfortunately dynamically generating preview examples like this is not possible :-( Lookbook uses [YARD](https://github.com/lsegal/yard) under the hood and as you correctly guessed it does static rather than dynamnic analysis on the preview files.

The closest you can get is using a YARD macro to avoid repetition - something line this:

```rb
  # @!macro [attach] generate_example
  #   This is a $1 icon
  def self.generate_example(icon)
    define_method(icon) do
      render Elements::ButtonComponent.new do
        icon
      end
      # render Generic::Icon::Component.new(icon: icon)
    end
  end

  generate_example "gear"
  generate_example "tablet"
  generate_example "exchange"
```

But you can't use a loop to add those `generate_example` method calls - each one needs adding by hand so it won't help much with what you are trying to achieve I don't think.

However, I think there are other options to achieve something _close_ to what you are trying to achieve.

The most straightforward one is to set up a single preview example method that uses a [preview template](https://viewcomponent.org/guide/previews.html#preview-templates). Within that template you are free to loop over your icons, render multiple components, whatever you like really. So it might look something like this:

```rb
# test/components/previews/icon_component_preview.rb
class IconComponentPreview < ViewComponent::Preview
  def all_icons
  end
end
```

```erb
<!-- test/components/previews/icon_component_preview/all_icons.html.erb -->
<% Generic::Icon::Component::ICONS.each do |icon| %>
  <%= render Generic::Icon::Component.new(icon: icon) %>
<% end %>
```

That will render a view with all your icons - and obviously you could wrap them in some html to get a nice grid layout or something working.

The downside to this is that the source code panel will show the contents of the `all_icons.html.erb` template file, so won't be particularly clear to other people on how to instantiate a new icon component. But you could always add a note to the `all_icons` method to clarify things if needed.

The other approach you could take is to render a single preview example, but set up a [dynamic preview param](https://lookbook.build/guide/previews/params) select field with the icons populated as the options. So you are only seeing one icon at a time but can pick from a list of icons to update the display dymanically.

Unfortunately, at the moment the list of icons for the select field would have to be hardcoded too - unless you were able to [load them from a JSON file](https://lookbook.build/guide/previews/params/#json-param-options). Adding support for being able to dynamically build those select options lists has been requested a number of times and is something I'm defintely investigating but is not yet possible.

It would be nice to have a better solution for what you are trying to achieve - displaying things like icon sets is a pretty common requirement and I'll try to have a think if there is anyway that use case could be supported better in the future. But until then I hope one or other of those options works for you.

**Comment by Timmitry** [comment]
Hey @allmarkedup, thanks a lot for your quick and thorough answer!

The solution with a custom template works really well for me 🎉 This way I can render each icon together with its name, which makes it easy to look up which icons are used, or to find the name of a specific icon:

```erb
<% Generic::Icon::Component::ICONS.each do |icon| %>
  <p>
    <%= render Generic::Icon::Component.new(icon:) %>
    <%= icon %>
  </p>
<% end %>
```

I added two previews, one for a single icon (which shows how to use the component), and one which uses the above template to render all icons together with their names:

```ruby
class Generic::Icon::ComponentPreview < ViewComponent::Preview
  def single
    render(Generic::Icon::Component.new(icon: :gear))
  end

  def all
    render_with_template(template: "generic/icon/template")
  end
end
```

The other approach with providing a dynamic preview param is therefore not needed, and wouldn't be as user friendly - as one would have to cycle through each item to see what it looks like 😉

**Comment by allmarkedup** [comment]
@Timmitry no worries, glad you've got a solution that works for you! The mix of the single icon preview and the 'all icons' preview template sounds great.

I'd still like to have a nicer, less manual solution for this sort of thing - you've got me thinking about it now :-) But it's good to know that you were able get close to your original intention with the tool as it is.
