### ISSUE TITLE
Log spamming issue with 1.1.0

### ISSUE THREAD

**Issue by trappar** [allmarkedup/lookbook#190]
I just tried updating to 1.1.0 (while in the process of testing to make sure the deadlock issue was resolved). For some reason on this version (and not on 1.0.8) as soon as I start my server I start getting these same two messages dumped into my `development.log` and to stdout over and over. Hard to tell how many of these there are, but it's in the order of thousands to tens of thousands of these lines per second:

> 17:10:52 web.1  | (silenced): "log/development.log"
> 17:10:52 web.1  | inotify: log/development.log ([:modify])

I'm guessing this might be some issue specific to my project's setup, but I'm not sure what config might be relevant. Any ideas?

**Comment by allmarkedup** [comment]
Hey @trappar, sorry you are running into more issues.

So by the looks of it I'd guess that what is happening is that the Listen gem is watching the log directory, and also logging changes to the log directory, resulting in an infinite loop.

Quite _why_ this is happening I'm not so sure. There have been some changes to logging in 1.1.0 which could be a factor here but really I don't think your log directory should not be being watched for changes regardless.

While I try to dig a bit deeper to see what is going on you can try the following in your app config:

```rb
config.lookbook.log_use_rails_logger = false
```

This should mean all Lookbook log messages are sent to `stdout` and not to whatever Rails logger you have configured which might avoid the loop being triggered.

Lookbook should only watch your components directory and your component previews directory for changes (unless you have specified additional paths to watch). If you are using `ActiveSupport::EventedFileUpdateChecker` as the [file watcher](https://guides.rubyonrails.org/configuring.html#config-file-watcher) in your app then a larger set of directories will be being watched but I haven't been able to find out anywhere if that includes the log directory - I would assume not but it may be the case.

If you have a chance to help validate this, in the top right corner of the Lookbook UI is a little `?` icon - if you click on that and then the 'copy debug data' link it should give you a JSON dump of resolved config settings. there should be an array of `listen_paths` in there somewhere that should look something like this:

```js
{
  "listen_paths": [
      "/Users/username/path/to/my-app/test/components/previews",
      "/Users/username/path/to/my-app/app/components"
  ]
}
```

If for some reason any of the paths in there are to the root of your app or anywhere unexpected then let me know.

Logging has been a constant pain in Lookbook due to the wide range of possible parent app configurations, but is something I'm going to try to focus on simplifying/improving as soon as I can. And if I can find anything that might be causing your issue in the meantime I'll get a quick fix out as soon as I can.

**Comment by trappar** [comment]
Turns out it was my fault. I had added a listen path that ended up evaluating to nil, which was somehow being transformed into the root directory of my project.

So this:
```ruby
config.lookbook.listen_paths += [nil]
```

Resulted in:
```json
{
    "listen_paths": [
      "/workspaces/project",
      "/workspaces/project/spec/components/previews",
      "/workspaces/project/app/components"
    ],
}
```

This could probably be prevented by changing the way that `normalize_paths` works here: https://github.com/allmarkedup/lookbook/blob/e323fc4fd87eb84dacb49bc4d578549ded7cc155/lib/lookbook/config.rb#L258-L264

I think this would do it:
```ruby
def normalize_paths(paths)
  paths.reject!(&:blank?).map! do |path|
    full_path = absolute_path(path)
    full_path if Dir.exist?(full_path)
  end.compact!
  paths
end
```

Though that would also prevent the valid relative path `""` from being transformed into the root path... (is that something that would even be a good idea to support...?)

Maybe `&:nil?` would be safer?

Regardless, I've got everything working now on my end. I'll leave it up to you if you want to fix this in the code here.

**Comment by allmarkedup** [comment]
@trappar thanks for the update and I'm glad you've got it sorted - Lookbook should definitely be guarding against that possibility so I'll add in a check to make sure something similar doesn't catch anyone else out. I'm just refactoring all the config handling anyway so will include it in that bit of work.

FWIW I'm also removing the overriding of the Listen logger - that should be left for the parent application to handle if required as most of the time I don't think it's useful to have logs filling up with file change info. That change will be in v1.1.1 (the config changes will come later).

Thanks again for getting back to me on this, I'll close this issue down now 👍
