### ISSUE TITLE
Lookbook sets action view logger to NullLogger by default

### ISSUE THREAD

**Issue by virolea** [allmarkedup/lookbook#67]
Hi ! 

We realised our app stopped logging action view related logs. After some investigation it looks like the ActionView logger is set to `Lookbook::NullLogger`.

After browsing Lookbook's source code it appears that this is the code responsible for this : 

https://github.com/allmarkedup/lookbook/blob/ac825a2782219089b15024da4567de1ac7554812/lib/lookbook/engine.rb#L76-L83

By default, Lookbook will nullify action view logs if `debug` is set to `false`. It feels like Lookbook config should not impact rails logging. What do you think ? 

I'm happy to propose a fix if it helps.

**Comment by allmarkedup** [comment]
Hey @virolea - you are right, this is a mistak, Lookbook should in no way change application-level configuration like this.

I'll try to get an update out this evening to fix this for you.

Many thanks for the report and sorry to cause you problems!

**Comment by virolea** [comment]
No worries, I appreciate you had a look at this on such a short notice 🙏🙂

**Comment by allmarkedup** [comment]
Hey again @virolea. I'm putting a release together that is hopefully going to go out next week so for now I have included the fix for this in the most recent beta (v0.7.2.beta.2) which is available on Rubygems now.

If you are happy to use the beta in the meantime I hope to get the full 0.7.2 release out soon but I'm just waiting to hear back from a few other people about whether it helps fix a couple of other issues that people have been having.

Let me know how you get on if you get a chance to test it but this version should no longer overwrite the action_view logger in the parent app. Thanks again for the bug report 👍

**Comment by virolea** [comment]
Hey @allmarkedup ! Works like a charm, thanks for taking care of this !
