### ISSUE TITLE
Missing partial action_text/contents/_content when component including actiontext

### ISSUE THREAD

**Issue by teddy-ma** [allmarkedup/lookbook#77]
After I upgrade from 0.7.1 to 0.7.2, the preview of component including model with actiontext broken.
![image](https://user-images.githubusercontent.com/788486/162421009-8047f189-ebf5-4809-bc7b-5b07f23e986b.png)
Here is a demo project that can reproduce this error. 
[lookbookdemo.zip](https://github.com/allmarkedup/lookbook/files/8451157/lookbookdemo.zip)

**Comment by allmarkedup** [comment]
Hey @teddy-ma - thanks for reporting this and for providing the demo project, it has made diving into this issue a lot easier.

So I've done some investigation and this is actually a bug in ViewComponent I believe. If you try to view your component using the 'standard' view component preview url (http://localhost:3000/rails/view_components/message_component/default) you will see it throws the same error. Lookbook  uses ViewComponent's preview controller to render previews under the hood.

The reason that it was working in versions <= 0.7.1 is because of a bug that was fixed here: https://github.com/allmarkedup/lookbook/commit/6b060a2e15b7151ee8f7a3e96935ff26c7ba1ce3 which meant that the preview controller `before_action`s were not being properly called. By some accident that somehow bypassed the issue at the ViewComponent end but as it's definitely a bug I don't want to roll that back.

I'd suggest opening an issue on the ViewComponent repo and seeing what they say. I have a suspicion that it is to do with the prepending of view paths in the preview controller but I'm not 100% sure yet.

I'll keep this issue open until it's been resolved one way or the other. Thanks!

**Comment by tkhobbes** [comment]
Is there any issue open on the main viewcomponent repository related to this?
