### ISSUE TITLE
Select param, when cast to Symbol, converts '~' option to :""

### ISSUE THREAD

**Issue by stevegeek** [allmarkedup/lookbook#92]
A select param "~" value results in a blank select option being rendered, which has a "" value. 

However if we rely on casting to symbol eg 

`@param my_param [symbol] select [~, option_1, option_2]` 

then selecting the blank actually results in a param value of `:""` 

My proposal here is for this to instead result in `nil` 

This could be achieved by changing the symbol type cast to ignore blanks , eg change https://github.com/allmarkedup/lookbook/blob/main/lib/lookbook/params.rb#L40 to 

`value.presence&.delete_prefix(":")&.to_sym`

**Comment by allmarkedup** [comment]
Hey @stevegeek - yes I agree that makes better sense for the symbol cast to resolve to `nil` and not an empty string. Good catch. Did you want to open a PR for this? Otherwise I'll try and get it updated and get a release out as soon as I can (probably over the weekend). Thanks for the suggestion :-)

**Comment by stevegeek** [comment]
Thanks @allmarkedup . If I have time later this week I will open a PR (unless you get to it first!)

**Comment by allmarkedup** [comment]
Hey @stevegeek - took me a little longer than planned but I've just put out v0.8.2 that contains this change in it.

Thanks again for the suggestion and let me know if you have any other issues 👍

**Comment by stevegeek** [comment]
Great thanks @allmarkedup !
